fragment LayoutQueryFragment on Query {
  global(relativePath: "index.json") {
    ...GlobalParts
  }
}

fragment ArtistQueryFragment on Query {
  artistSeo(relativePath: "index.md"){
    ...ArtistSeoParts
  }
}

fragment PostsQueryFragment on Query {
  PostsSeo(relativePath: "index.md"){
    ...PostsSeoParts
  }
}

# fragment EventsQueryFragment on Query {
#   EventsSeo(relativePath: "index.md"){
#     ...EventsSeoParts
#   }
# }



